x-github-actions-runner: &github-actions-runner
  build:
    context: ./build-context
    args:
      RUNNER_VERSION: "2.283.2"
      USER_ID: "${USER_ID}"
      GROUP_ID: "${GROUP_ID}"
      DOCKER_GROUP_ID: "${DOCKER_GROUP_ID}"
      TZ: "${TZ:-Etc/UTC}"
  restart: unless-stopped
  image: local-github-actions-runner:latest
  tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"

version: "3.9"
services:
  github-actions-runner:
    <<: *github-actions-runner
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build:/home/actions/actions-runner/workspace/_build
